version: '3'

services:
  frontend:
    container_name: cbt-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules      
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    container_name: cbt-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  backend:
    container_name: cbt-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_HOST=cbt-db
      - DB_DATABASE=cityboardtorrejon
      - DB_USERNAME=cbt_user
      - DB_PASSWORD=cbt_password
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: cbt-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cityboardtorrejon
      MYSQL_USER: cbt_user
      MYSQL_PASSWORD: cbt_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/torrejon.sql:/docker-entrypoint-initdb.d/torrejon.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge